# Generated by Django 3.2 on 2021-04-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certification',
            field=models.CharField(choices=[('DO', 'Osteopathic Doctor'), ('MD', 'Medical Doctor')], default='DO', max_length=2),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.CharField(default='', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
